name: casbindart
maintainer: Romit Karmakar (@romitkarmakar)
description: Casbin Dart helps to simplify policy management.
homepage: https://github.com/romitkarmakar/dart-yaml
version: 1.0.0+0

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.14.2